Homework/config/routes.rb
Rails.application.routes.draw do
  devise_for :customers,controllers: {
        sessions: 'customers/sessions',
        registrations: 'customers/registrations'
      }
  devise_for :admins,controllers: {
        sessions: 'admins/sessions'
      }
  resources :admins,only:[:index]
  resources :customers,only:[:index]
  resources :bookings,except:[:edit,:update]
  resources :cleaners,:cities
  root 'customers#index'
  match '*path' => redirect('/404'), via: :get
end

Homework/app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Homework</title>
    <%= stylesheet_link_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <%= link_to "Homework",admins_path,class:"navbar-brand"%>
        </div>
        <ul class="nav navbar-nav">
          <li><%= link_to "Manage Cities",cities_path%></li>
          <li><%= link_to "Manage Cleaners",cleaners_path%></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Welcome #{current_admin.email}" %></li>
          <li><%= link_to destroy_admin_session_path,method:'delete' do%><span class="glyphicon glyphicon-log-out"></span>Logout<% end %></li>
        </ul>
      </div>
    </nav>
    <div class="container">
      <%if notice %><p class="notice"><%= notice %></p><% end %>
      <%if alert %><p class="alert"><%= alert %></p><% end %>
      <%= yield %>
    </div>
  </body>
</html>

Homework/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Login - Homework</title>
    <%= stylesheet_link_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <ul class="nav navbar-nav">
          <li><%= link_to "Admin Login",new_admin_session_path %></li>
          <li><%= link_to "Customer Login",new_customer_session_path %></li>
        </ul>
      </div>
    </nav>
    <div class="container">
      <%if notice %><p class="notice"><%= notice %></p><% end %>
      <%if alert %><p class="alert"><%= alert %></p><% end %>
      <%= yield %>
    </div>
  </body>
</html>

Homework/app/views/layouts/customers.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Homework</title>
    <%= stylesheet_link_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
            <%= link_to "Homework",customers_path,class:"navbar-brand"%>
        </div>
        <ul class="nav navbar-nav">
          <li><%= link_to "Edit Profile",edit_customer_registration_path%></li>
          <li><%= link_to "Book Cleaner",new_booking_path%></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Welcome #{current_customer.email}"%></li>
          <li><%=link_to destroy_customer_session_path,method:'delete' do%><span class="glyphicon glyphicon-log-out"></span>Logout<% end %></li>
        </ul>
      </div>
    </nav>
    <div class="container">
      <%if notice %><p class="notice"><%= notice %></p><% end %>
      <%if alert %><p class="alert"><%= alert %></p><% end %>
      <%= yield %>
    </div>
  </body>
</html>