Homework/config/routes.rb
Rails.application.routes.draw do
  devise_for :customers,controllers: {
        sessions: 'customers/sessions',
        registrations: 'customers/registrations'
      }
  devise_for :admins,controllers: {
        sessions: 'admins/sessions'
      }
  resources :admins,only:[:index]
  resources :customers,only:[:index]
  resources :bookings,except:[:edit,:update]
  resources :cleaners,:cities
  root 'customers#index'
  match '*path' => redirect('/404'), via: :get
end

Homework/app/models/cleaner.rb
class Cleaner < ApplicationRecord
  has_and_belongs_to_many :cities,dependent: :destroy
  has_many :bookings,dependent: :destroy

  EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/
  validates :first_name,presence:true
  validates :last_name,presence:true
  validates :quality_score,presence:true
  validates :email,presence:true
  validates :email, format: { with:EMAIL_REGEX ,
                              message: "Please Enter valid email address" }
  validates :quality_score, numericality: true
  validates :quality_score, inclusion:{in:(0..5)}


end

Homework/app/controllers/cleaners_controller.rb
class CleanersController < ApplicationController
before_action :authenticate_admin!
before_action :load_city,only:[:new,:create,:edit,:update]
before_filter :load_cleaner,except:[:index,:new,:create]
layout 'admin'




  def index
    @cleaners = Cleaner.all
  end

  def new
    @cities = []
    @cleaner = Cleaner.new
  end

  def create
    @cities = []
    @cleaner = Cleaner.new(cleaner_params)
    if @cleaner.save
      params[:city_ids].each do |id|
        CitiesCleaner.create(city_id:id,cleaner_id:@cleaner.id)
      end
      redirect_to @cleaner
    else
      render :new
    end
  end

  def edit
    if @cleaner.present?
      @cities = @cleaner.cities.pluck(:id)
    else
      flash[:alert] = "Something Went Wrong"
      redirect_to cleaners_path
    end
  end

  def update
    if @cleaner.update(cleaner_params)
      CitiesCleaner.where(cleaner_id:@cleaner.id).destroy_all
      params[:city_ids].each do |id|
        CitiesCleaner.create(city_id:id,cleaner_id:@cleaner.id)
      end
      redirect_to @cleaner
    else
      render :edit
    end
  end

  def show
    if @cleaner.present?
      @city_names = @cleaner.cities.pluck(:city_name)
    else
      flash[:alert] = "Something Went Wrong"
      redirect_to cleaners_path
    end
  end

  def destroy
    @cleaner.destroy
    redirect_to cleaners_path
  end

  private
  def cleaner_params
    params.require(:cleaner).permit(:first_name, :last_name, :quality_score, :email)
  end

  def load_city
    @city = City.all
  end

  def load_cleaner
    @cleaner = Cleaner.find_by(id:params[:id])
  end

end

Homework/app/helpers/cleaners_helper.rb
module CleanersHelper
  def get_full_name(cleaner)
    "#{cleaner.first_name} #{cleaner.last_name}"
  end
end

Homework/app/views/cleaners/_form.html.erb
<%= form_for(@cleaner,html:{class:'form-horizontal'}) do |f| %>
  <% if @cleaner.errors.any? %>
    <div id="error_explanation">
      <ul>
        <% @cleaner.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.label :first_name %>
  <div class="form-group">
    <div class="col-xs-5">
      <%= f.text_field :first_name ,class:'form-control'%>
    </div>
  </div>

  <%= f.label :last_name %>
  <div class="form-group">
    <div class="col-xs-5">
      <%= f.text_field :last_name ,class:'form-control' %>
    </div>
  </div>

  <%= f.label :quality_score %>
  <div class="form-group">
    <div class="col-xs-5">
      <%= f.text_field :quality_score ,class:'form-control' %>
    </div>
  </div>

  <%= f.label :email %>
  <div class="form-group">
    <div class="col-xs-5">
      <%= f.email_field :email ,class:'form-control' %>
    </div>
  </div>

  <%= f.label :"City:" %>
  <% @city.each do |city| %>
    <% if @cities.include?city.id %>
      <div class="form_group">
        <%= check_box_tag 'city_ids[]',city.id,checked:true %>
        <%= h city.city_name %>
      </div>
    <% else %>
      <div class="form_group">
        <%= check_box_tag 'city_ids[]', city.id %>
        <%= h city.city_name %>
      </div>
    <% end %>
  <% end %>
  <br/>

  <%= f.submit class:'btn btn-default'%>
  
<% end %>

Homework/app/views/cleaners/edit.html.erb
<%= render 'form' %>

<%= link_to "Back",cleaners_path %>

Homework/app/views/cleaners/index.html.erb
<%= button_to :"Add Cleaner",new_cleaner_path,method:'get',class:'btn btn-default'%><br/>
<table class="table table-hover table-striped">
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Quality Score</th>
    <th>City</th>
    <th colspan="3">Action</th>
  </tr>
  <% if @cleaners.present?%>
    <% @cleaners.each do |cleaner| %>
      <tr>
        <td><%= get_full_name(cleaner) %></td>
        <td><%= cleaner.email%></td>
        <td><%= cleaner.quality_score%></td>
        <td><%= cleaner.cities.map{|city| city.city_name}.join(',') %></td>
        <td><%= link_to cleaner_path(cleaner.id) do%><span class="glyphicon glyphicon-eye-open"/><% end %></td>
        <td><%= link_to edit_cleaner_path(cleaner.id) do%><span class="glyphicon glyphicon-pencil"/><% end %></td>
        <td><%= link_to cleaner_path(cleaner.id),method:'delete',data:{confirm:'Are you sure?'} do%><span class="glyphicon glyphicon-trash"/><% end %></td>
      </tr>
    <% end %>
  <% else %>
    <tr>
      <td colspan="7" align="center">No Records found.</td>
    </tr>
  <% end %>
</table>

Homework/app/views/cleaners/new.html.erb
<%= render 'form' %>

<%= link_to "Back",cleaners_path %>

Homework/app/views/cleaners/show.html.erb
<p>
  <strong>First name:</strong>
  <%= @cleaner.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @cleaner.last_name %>
</p>

<p>
  <strong>Quality score:</strong>
  <%= @cleaner.quality_score %>
</p>

<p>
  <strong>City:</strong>
  <br/>
  <% @city_names.each do |city| %>
    <%= city %><br/>
  <% end %>
</p>

<%= link_to :back,cleaners_path %>