Homework/config/routes.rb
Rails.application.routes.draw do
  devise_for :customers,controllers: {
        sessions: 'customers/sessions',
        registrations: 'customers/registrations'
      }
  devise_for :admins,controllers: {
        sessions: 'admins/sessions'
      }
  resources :admins,only:[:index]
  resources :customers,only:[:index]
  resources :bookings,except:[:edit,:update]
  resources :cleaners,:cities
  root 'customers#index'
  match '*path' => redirect('/404'), via: :get
end

Homework/app/models/city.rb
class City < ApplicationRecord
  has_and_belongs_to_many :cleaners,dependent: :destroy
  has_many :bookings,dependent: :destroy

  validates :city_name,presence:true
  validates_uniqueness_of :city_name
end

Homework/app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  before_action :authenticate_admin!
  before_filter :load_city,except:[:index,:new,:create]
  layout 'admin'

  def load_city
    @city = City.find_by(id:params[:id])
  end

  def index
    @cities = City.all
  end

  def new
    @city = City.new
  end

  def create
    @city = City.new(city_params)
    if @city.save
      redirect_to @city
    else
      render :new
    end
  end

  def show
    if @city.present?
      @cleaners_in_city = []
      @city.cleaners.each do |cleaner|
        @cleaners_in_city.push(cleaner)
      end
    else
      flash[:alert] = "Something Went Wrong"
      redirect_to cities_path
    end
  end

  def edit
    if @city.nil?
      flash[:alert] = "Something Went Wrong"
      redirect_to cities_path
    end
  end

  def update
    if @city.update(city_params)
      redirect_to @city
    else
      render :edit
    end
  end

  def destroy
    @city.destroy
    redirect_to cities_path
  end

  private
  def city_params
    params.require(:city).permit(:city_name)
  end
end

Homework/app/helpers/cities_helper.rb
module CitiesHelper
end

Homework/app/views/cities/_form.html.erb
<%= form_for(@city,html:{class:'form-inline'}) do |f| %>
  <%= f.label :name %>
  <div class="form-group">
    <div class="col-xs-5">
      <%= f.text_field :city_name,class:'form-control' %>
    </div>
  </div>
  <%= f.submit class:'btn btn-default' %>
<% end %>

Homework/app/views/cities/edit.html.erb
<%= render 'form' %>
<br/>
<%= link_to :back,cities_path %>

Homework/app/views/cities/index.html.erb
<%= button_to :"Add City",new_city_path,method:'get',class:'btn btn-default'%><br/>
<table class="table table-hover table-striped" style="width:30%;">
  <tr>
    <th>City Name</th>
    <th colspan="3">Action</th>
  </tr>
  <% if @cities.present?%>
    <% @cities.each do |city| %>
      <tr>
        <td><%= city.city_name %></td>
        <td><%= link_to city_path(city.id) do%><span class="glyphicon glyphicon-eye-open"/><% end %></td>
        <td><%= link_to edit_city_path(city.id) do%><span class="glyphicon glyphicon-pencil"/><% end %></td>
        <td><%= link_to city_path(city.id),method:'delete',data: { confirm:'Are you sure?'} do%><span class="glyphicon glyphicon-trash"/><% end %> </td>
      </tr>
    <% end %>
  <% else %>
    <tr>
      <td colspan="4" align="center">No Record Found</td>
    </tr>
  <% end %>
</table>

Homework/app/views/cities/new.html.erb
<%= render 'form' %>
<br/>
<%= link_to :Back,cities_path %>

Homework/app/views/cities/show.html.erb
<p>
  <strong>City Name:</strong>
  <%= @city.city_name %>
</p>

<p>
  <strong>Cleaners in this city:</strong><br/>
  <% @cleaners_in_city.each do |cleaner| %>
    <%= cleaner.first_name%> <%=cleaner.last_name%><br/>
  <% end %>
</p>

<%= link_to :back,cities_path %>